server:
  port: 8080

spring:
  application:
    name: ads-api-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.63.128:9030/ads?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ""
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info
